//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 18 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Instagram
      ///
      /// Key: Instagram
      ///
      /// Locales: en
      var instagram: RswiftResources.StringResource { .init(key: "Instagram", tableName: "Localizable", source: source, developmentValue: "Instagram", comment: nil) }

      /// en translation: user_account_name
      ///
      /// Key: account
      ///
      /// Locales: en
      var account: RswiftResources.StringResource { .init(key: "account", tableName: "Localizable", source: source, developmentValue: "user_account_name", comment: nil) }

      /// en translation: johnnydepp 🔥🔥🔥
      ///
      /// Key: commentLabel
      ///
      /// Locales: en
      var commentLabel: RswiftResources.StringResource { .init(key: "commentLabel", tableName: "Localizable", source: source, developmentValue: "johnnydepp 🔥🔥🔥", comment: nil) }

      /// en translation: dialogs
      ///
      /// Key: dialogs
      ///
      /// Locales: en
      var dialogs: RswiftResources.StringResource { .init(key: "dialogs", tableName: "Localizable", source: source, developmentValue: "dialogs", comment: nil) }

      /// en translation: Wright message here...
      ///
      /// Key: directDialogPlaceholder
      ///
      /// Locales: en
      var directDialogPlaceholder: RswiftResources.StringResource { .init(key: "directDialogPlaceholder", tableName: "Localizable", source: source, developmentValue: "Wright message here...", comment: nil) }

      /// en translation: Your notes
      ///
      /// Key: directNotesAccountOwnerText
      ///
      /// Locales: en
      var directNotesAccountOwnerText: RswiftResources.StringResource { .init(key: "directNotesAccountOwnerText", tableName: "Localizable", source: source, developmentValue: "Your notes", comment: nil) }

      /// en translation: Note...
      ///
      /// Key: directNotesSampleText
      ///
      /// Locales: en
      var directNotesSampleText: RswiftResources.StringResource { .init(key: "directNotesSampleText", tableName: "Localizable", source: source, developmentValue: "Note...", comment: nil) }

      /// en translation: Email
      ///
      /// Key: email
      ///
      /// Locales: en
      var email: RswiftResources.StringResource { .init(key: "email", tableName: "Localizable", source: source, developmentValue: "Email", comment: nil) }

      /// en translation: Follow
      ///
      /// Key: follow
      ///
      /// Locales: en
      var follow: RswiftResources.StringResource { .init(key: "follow", tableName: "Localizable", source: source, developmentValue: "Follow", comment: nil) }

      /// en translation: json
      ///
      /// Key: json
      ///
      /// Locales: en
      var json: RswiftResources.StringResource { .init(key: "json", tableName: "Localizable", source: source, developmentValue: "json", comment: nil) }

      /// en translation: Likes: 143 569
      ///
      /// Key: likesLabel
      ///
      /// Locales: en
      var likesLabel: RswiftResources.StringResource { .init(key: "likesLabel", tableName: "Localizable", source: source, developmentValue: "Likes: 143 569", comment: nil) }

      /// en translation: Loading...
      ///
      /// Key: loading
      ///
      /// Locales: en
      var loading: RswiftResources.StringResource { .init(key: "loading", tableName: "Localizable", source: source, developmentValue: "Loading...", comment: nil) }

      /// en translation: Message
      ///
      /// Key: message
      ///
      /// Locales: en
      var message: RswiftResources.StringResource { .init(key: "message", tableName: "Localizable", source: source, developmentValue: "Message", comment: nil) }

      /// en translation: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      ///
      /// Key: messagePreviewLabel
      ///
      /// Locales: en
      var messagePreviewLabel: RswiftResources.StringResource { .init(key: "messagePreviewLabel", tableName: "Localizable", source: source, developmentValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", comment: nil) }

      /// en translation: Search
      ///
      /// Key: searshBarPlaceholder
      ///
      /// Locales: en
      var searshBarPlaceholder: RswiftResources.StringResource { .init(key: "searshBarPlaceholder", tableName: "Localizable", source: source, developmentValue: "Search", comment: nil) }

      /// en translation: Show Profile
      ///
      /// Key: showProfile
      ///
      /// Locales: en
      var showProfile: RswiftResources.StringResource { .init(key: "showProfile", tableName: "Localizable", source: source, developmentValue: "Show Profile", comment: nil) }

      /// en translation: elon_official
      ///
      /// Key: userNameLabel
      ///
      /// Locales: en
      var userNameLabel: RswiftResources.StringResource { .init(key: "userNameLabel", tableName: "Localizable", source: source, developmentValue: "elon_official", comment: nil) }

      /// en translation: users
      ///
      /// Key: users
      ///
      /// Locales: en
      var users: RswiftResources.StringResource { .init(key: "users", tableName: "Localizable", source: source, developmentValue: "users", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 6 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `gradientOrange`.
    var gradientOrange: RswiftResources.ColorResource { .init(name: "gradientOrange", path: [], bundle: bundle) }

    /// Color `gradientPink`.
    var gradientPink: RswiftResources.ColorResource { .init(name: "gradientPink", path: [], bundle: bundle) }

    /// Color `gradientPurple`.
    var gradientPurple: RswiftResources.ColorResource { .init(name: "gradientPurple", path: [], bundle: bundle) }

    /// Color `gradientRed`.
    var gradientRed: RswiftResources.ColorResource { .init(name: "gradientRed", path: [], bundle: bundle) }

    /// Color `profileButtonBackground`.
    var profileButtonBackground: RswiftResources.ColorResource { .init(name: "profileButtonBackground", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `insta-logo`.
    var instaLogo: RswiftResources.ImageResource { .init(name: "insta-logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 4 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `dialogs.json`.
    var dialogsJson: RswiftResources.FileResource { .init(name: "dialogs", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `posts.json`.
    var postsJson: RswiftResources.FileResource { .init(name: "posts", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `stories.json`.
    var storiesJson: RswiftResources.FileResource { .init(name: "stories", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `users.json`.
    var usersJson: RswiftResources.FileResource { .init(name: "users", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }
  }
}